version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - '55432:5432'
  webapp:
    build: .
    restart: unless-stopped
    links:
      - postgres:postgres
    ports:
      - '56484:8080'
    expose:
      - 56484
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/
    volumes:
      - /files:/files

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450