server.port: 8080


spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/download_server}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

files-path: "C:\\files"